FROM ubuntu:14.04
MAINTAINER cheng <cheng@example.org>
ENV REFRESHED_AT 2017-7-6

COPY ["sources.list","/etc/apt/"]
RUN apt-get -y update
RUN apt-get -y install ruby2.0 ruby-dev make nodejs
RUN gem sources --remove https://rubygems.org/
RUN gem sources --remove http://rubygems.org/
RUN gem sources --add http://gems.ruby-china.org/
RUN cd /usr/bin/
RUN ln -sf /usr/bin/ruby2.0 /usr/bin/ruby
RUN ln -sf /usr/bin/gem2.0 /usr/bin/gem
RUN ln -sf /usr/bin/erb2.0 /usr/bin/erb
RUN ln -sf /usr/bin/irb2.0 /usr/bin/irb
RUN ln -sf /usr/bin/rake2.0 /usr/bin/rake
RUN ln -sf /usr/bin/rdoc2.0 /usr/bin/rdoc
RUN ln -sf /usr/bin/testrb2.0 /usr/bin/testrb
RUN apt-get -y install ruby2.0-dev
RUN ruby -v
RUN gem install --no-rdoc --no-ri jekyll -v 2.5.3

VOLUME /data
VOLUME /var/www/html
WORKDIR /data

ENTRYPOINT ["jekyll", "build", "--destination=/var/www/html"]
